SET DEFAULT_STORAGE_ENGINE = INNODB;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS kits (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    kit INT NOT NULL,
    contents TEXT NOT NULL,
    ec_contents TEXT NOT NULL
    ) CHARACTER SET utf8
    COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    kit INT NOT NULL,
    smartAutoKit BOOLEAN NOT NULL
) CHARACTER SET utf8
    COLLATE utf8_unicode_ci;