name: WeirdoKits
version: '${version}'
main: club.revived.WeirdoKits
api-version: '1.20'
author: yyuh
description: "Credits: §aVertrauterDavid"
website: https://github.com/Omnikeck
commands:
  e:
  getec:
  getkit:
  viewkit:
  viewec:
  ec2:
  ec3:
  ec4:
  ec5:
  ec6:
  ec7:
  ec1:
  kit:
  kits:
  kit1:
  k1:
  kit2:
  k:
  k2:
  kit3:
  k3:
  kit4:
  k4:
  kit5:
  k5:
  kit6:
  k6:
  kit7:
  k7:
  kit8:
  k8:
  kit9:
  k9: